FROM postgis/postgis:16-3.4

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgis \
        postgresql-16-postgis-3 \
        postgresql-16-postgis-3-scripts \
    && rm -rf /var/lib/apt/lists/*